export const TYPES = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    GET_MENU: "GET_MENU",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILED: "LOGIN_USER_FAILED",
    LOGIN_USER_LOADING: "LOGIN_USER_LOADING",
}